# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaccept',
            name='addressac',
            field=models.ForeignKey(help_text='地址信息', on_delete=django.db.models.deletion.CASCADE, to='user_operation.UserAddress', verbose_name='地址信息'),
        ),
        migrations.AddField(
            model_name='orderaccept',
            name='orderac',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='订单'),
        ),
    ]
