# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20190214_1921'),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaccept',
            name='useroac',
            field=models.ForeignKey(help_text='接单人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接单人'),
        ),
        migrations.AddField(
            model_name='order',
            name='currentaddress',
            field=models.ForeignKey(blank=True, help_text='下单地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_operation.UserAddress', verbose_name='下单地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='currentuser',
            field=models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_user', related_query_name='orders_order_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
