# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayOrderSettle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(blank=True, help_text='商户订单号', max_length=50, null=True, verbose_name='商户订单号')),
                ('alipay_trade_no', models.CharField(blank=True, help_text='支付宝交易号', max_length=50, null=True, verbose_name='支付宝交易号')),
                ('order_id', models.IntegerField(blank=True, help_text='订单id', null=True, verbose_name='订单id')),
                ('out_request_no', models.CharField(blank=True, help_text='结算流水号', max_length=50, null=True, verbose_name='结算流水号')),
                ('trans_out', models.CharField(blank=True, help_text='支出方用户号', max_length=20, null=True, verbose_name='支出方用户号')),
                ('trans_in', models.CharField(blank=True, help_text='收入方用户号', max_length=20, null=True, verbose_name='收入方用户号')),
                ('amount', models.FloatField(default=0, help_text='支付金额', verbose_name='支付金额')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 2, 14, 19, 21, 33, 338614), help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '支付宝结算',
                'verbose_name_plural': '支付宝结算',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_point', models.CharField(default='', help_text='地址坐标', max_length=100, verbose_name='地址坐标')),
                ('address', models.CharField(default='', help_text='地址', max_length=100, verbose_name='地址')),
                ('user_name', models.CharField(default='', help_text='姓名', max_length=20, verbose_name='姓名')),
                ('user_mobile', models.CharField(help_text='联系电话', max_length=11, verbose_name='联系电话')),
                ('city', models.CharField(default='', help_text='所在城市', max_length=40, verbose_name='所在城市')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 2, 14, 19, 21, 33, 339485), help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.CreateModel(
            name='UserAli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, help_text='支付宝昵称', max_length=30, null=True, verbose_name='支付宝昵称')),
                ('avatar', models.CharField(blank=True, help_text='用户头像地址', max_length=300, null=True, verbose_name='用户头像地址')),
                ('userali_id', models.CharField(blank=True, help_text='支付宝id', max_length=50, null=True, verbose_name='支付宝id')),
            ],
            options={
                'verbose_name': '用户支付宝',
                'verbose_name_plural': '用户支付宝',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问')], default=1, help_text='留言类型：(1)留言,(2)投诉,(3)询问', verbose_name='消息类型')),
                ('subject', models.CharField(default='', help_text='主题', max_length=100, verbose_name='主题')),
                ('message', models.TextField(default='', help_text='留言内容', verbose_name='留言内容')),
                ('file', models.FileField(default='', help_text='上传文件', upload_to='message/', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 2, 14, 19, 21, 33, 340193), help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
            },
        ),
    ]
